# -*- coding: utf-8 -*-
"""Análise_de_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FMdB5zjMwuJV-Lsms95xIKgsYnw6wZRm
"""

import pandas as pd
tabela = pd.read_csv(r"C:\Users\Vinicius Costa\Desktop\Jupyter\dados\telecom_users.csv")

# tratamento de dados

#axis -> 0 = linha
#axis -> 1 = coluna

tabela = tabela.drop("Unnamed: 0", axis = 1)

# resolver valores que estão sendo reconhecidos de forma errada (tipo)

tabela["TotalGasto"] = pd.to_numeric(tabela["TotalGasto"], errors="coerce")

#excluindo as colunas que tem todos os valores vazios

tabela = tabela.dropna(how="all",axis=1)

#excluindo as linhas que tem pelo menos um valor vazio

tabela = tabela.dropna(how="any",axis=0)

display(tabela)
print(tabela.info())

# Análise inicial

print(tabela["Churn"].value_counts(normalize=True).map("{0:.1%}".format))

#Análise detalhada
import plotly.express as px
for coluna in tabela.columns:
    
    grafico = px.histogram(tabela, x=coluna, color ="Churn", text_auto=True)

    grafico.show()

    # para cada coluna da minha tabela eu quero um gráfico

"""
Conclusões

- Pessoas com familias maiores tendem a cancelar menos
    - Promoções para familias maiores

- Clientes nos primeiros meses tem uma tendência bem maior de cancelar
    - pode ser um marketing muito agressivo
    - pode ser que a experiência nos primeiros meses seja ruim
    - posso fazer uma promoção de no primeiro ano é mais barato

- Quanto mais serviços o cliente posssui, menos ele cancela
    - podemos oferecer mais serviços de graça ou por um preço muito menor

- Quase todos os cancelamentos então na assinatura mensal
    - Oferece desconto anual, 2 anos
    
- No boleto eletrônico quase metade desistiram
    - dar desconto no cartão

"""

!pip install plotly