# -*- coding: utf-8 -*-
"""Automação_web_(Web Scraping).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bO5DkDGfvMGytfFKk9_aQpzgFflJ7Tkx
"""

#!pip install selenium

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import pandas as pd

# Abrindo o navegador

navegador = webdriver.Chrome()

# indo para a página do Google

navegador.get("https://www.google.com/")

# pegando o valor da cotação do Dólar

navegador.find_element(By.XPATH,
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar")

navegador.find_element(By.XPATH,
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

cotacao_dolar = navegador.find_element(By.XPATH,
    '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value") 

# pegando o valor da cotação do Euro

navegador.get("https://www.google.com/")

navegador.find_element(By.XPATH,
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação euro")

navegador.find_element(By.XPATH,
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

cotacao_euro = navegador.find_element(By.XPATH,
    '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value") 

# pegando a cotação do Ouro
navegador.get("https://www.melhorcambio.com/ouro-hoje")

cotacao_ouro = navegador.find_element(By.XPATH,
    '//*[@id="comercial"]').get_attribute("value")
cotacao_ouro = cotacao_ouro.replace(",",".")

navegador.quit()

print(cotacao_dolar)
print(cotacao_euro)
print(cotacao_ouro)

# importando a base de dados e atualizando a base

tabela = pd.read_excel(r"C:\Users\Vinicius Costa\Desktop\Jupyter\dados\Produtos.xlsx")
display(tabela)

# cotação Dólar
    
tabela.loc[tabela["Moeda"] == "Dólar","Cotação"] = float(cotacao_dolar)

# cotação Euro

tabela.loc[tabela["Moeda"] == "Euro","Cotação"] = float(cotacao_euro)

# cotação Ouro

tabela.loc[tabela["Moeda"] == "Ouro","Cotação"] = float(cotacao_ouro)

# atualizando o preço de compra

tabela["Preço de Compra"] = tabela["Cotação"] * tabela["Preço Original"]

# atualizando o preço de venda

tabela["Preço de Venda"] = tabela["Preço de Compra"] * tabela["Margem"]

# formatando os preços
tabela["Preço de Venda"] = tabela["Preço de Venda"].map("R$ {:,.2f}".format)
tabela["Preço de Compra"] = tabela["Preço de Compra"].map("R$ {:,.2f}".format)
display(tabela)
tabela.to_excel(r"C:\Users\Vinicius Costa\Desktop\Jupyter\dados\Produtos_novo.xlsx")

# importando a base de dados e atualizando a base
import pandas as pd

tabela = pd.read_excel(r"C:\Users\Vinicius Costa\Desktop\Jupyter\dados\Produtos.xlsx")
display(tabela)

# cotação Dólar
    
tabela.loc[tabela["Moeda"] == "Dólar","Cotação"] = float(cotacao_dolar)

# cotação Euro

tabela.loc[tabela["Moeda"] == "Euro","Cotação"] = float(cotacao_euro)

# cotação Ouro

tabela.loc[tabela["Moeda"] == "Ouro","Cotação"] = float(cotacao_ouro)

# atualizando o preço de compra

tabela["Preço de Compra"] = tabela["Cotação"] * tabela["Preço Original"]

# atualizando o preço de venda

tabela["Preço de Venda"] = tabela["Preço de Compra"] * tabela["Margem"]

# formatando os preços
tabela["Preço de Venda"] = tabela["Preço de Venda"].map("R$ {:,.2f}".format)
tabela["Preço de Compra"] = tabela["Preço de Compra"].map("R$ {:,.2f}".format)
display(tabela)
tabela.to_excel("C:\Users\Vinicius Costa\Desktop\Jupyter\dados\Produtos_novo.xlsx")

