# -*- coding: utf-8 -*-
"""Cópia de Automação_local_(pyautogui).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GQ4wMJvv3c4dVwKmXLsoVAVcT51sqme7

Texto aleatório
"""

import pyautogui
import pyperclip
import time

pyautogui.PAUSE = 2

pyautogui.press('win')
pyautogui.write('bloco')
pyautogui.press('enter')

time.sleep(3)

pyperclip.copy('Te amo meu amor, você é incrível <3')
pyautogui.hotkey('ctrl','v')

print('hello world')

!pip install pyautogui

import pyautogui
import pyperclip
import time
import pandas as pd

pyautogui.PAUSE = 3

pyautogui.hotkey('ctrl','t')
pyperclip.copy('https://drive.google.com/drive/folders/149xknr9JvrlEnhNWO49zPcw0PW5icxga')
pyautogui.hotkey('ctrl','v')
pyautogui.press('enter')

time.sleep(2)

pyautogui.click(x=344, y=297, clicks = 2)
pyautogui.click(x=390, y=345)
pyautogui.click(x=1160, y=189)
pyautogui.click(x=860, y=630)

time.sleep(6)

tabela = pd.read_excel(r"C:\Users\Vinicius Costa\Desktop\Jupyter\dados\VendasDez.xlsx")

faturamento = tabela["Valor Final"].sum()
quantidade = tabela["Quantidade"].sum()


pyautogui.click(x=806, y=508)
#time.sleep(1)
pyautogui.hotkey('ctrl','t')
pyperclip.copy('https://mail.google.com/mail/u/0/#inbox')
pyautogui.hotkey('ctrl','v')
pyautogui.press('enter')

time.sleep(4)

pyautogui.click(x=162, y=196)
pyautogui.write('vinicius123cs2@gmail.com')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.write('Recursos')
pyautogui.press('tab')
pyautogui.write(f'Prezados, bom dia\n\nO faturamento foi de R${faturamento:,.2f}\nA quantidade vendida foi de {quantidade:,} unidades')
pyautogui.click(x=854, y=639)

import pyautogui
import time
time.sleep(5)
pyautogui.position()

import pandas as pd
tabela = pd.read_excel(r"C:\Users\Vinicius Costa\Desktop\Jupyter\dados\VendasDez.xlsx")
display(tabela)

faturamento = tabela["Valor Final"].sum()
quantidade = tabela["Quantidade"].sum()

print(faturamento)
print(quantidade)

pyautogui.press('ctrl','t')
pyperclip.copy('https://mail.google.com/mail/u/0/#inbox')
pyautogui.press('ctrl','v')
pyautogui.click(x=162, y=196)
pyautogui.write('vinicius123cs2@gmail.com')
pyautogui.press('tab')
pyperclip.copy('Análises')
pyautogui.press('crtl','v')
pyautogui.press('tab')
pyautogui.write('O Faturamento foi de R${}\nA Quantidade vendida foi de {} unidades'.format(faturamento,quantidade))
pyautogui.click(x=854, y=639)

pyautogui.press('ctrl','t')
pyperclip.copy('https://mail.google.com/mail/u/0/#inbox')
pyautogui.press('ctrl','v')
pyautogui.click(x=162, y=196)
pyautogui.write('vinicius123cs2@gmail.com')
pyautogui.press('tab')
pyperclip.copy('Análises')
pyautogui.press('crtl','v')
pyautogui.press('tab')
pyautogui.write('O Faturamento foi de R${}\nA Quantidade vendida foi de {} unidades'.format(faturamento,quantidade))

!pip install openpyxl

!pip install pandas

